### ISSUE TITLE
I'm stumped

### ISSUE THREAD

**Issue by SandorMax** [guideguide/support#100]
I've been using GuideGuide successfully for almost a year and I'm stumped. I've got a 969px x 1330px PSD file. I have 0px margins. 8 col x 108px and 7 gut x 15px = 969. the first time I did this I got 8 columns and 7 gutters but when i went to added 100px to the doc width I had an extra gutter on the right side. Then i tried it again and no guides are appearing at all. 
![screen shot 2015-01-08 at 12 45 03 pm](https://cloud.githubusercontent.com/assets/10453015/5667307/c122fe3e-9734-11e4-97e6-d9f32d8014dd.png)

**Comment by cameronmcefee** [comment]
Hi @SandorMax,

It sounds like you have two separate issues here. Let's tackle the guides that don't appear first. My theory is that you may have just hidden the guides so they're there, just not visible. Try toggling the the guide visibility.

As for the extra gutter you see, That one comes down to math. You've specified the number of columns, the width of the columns, and the width of the gutters, so you will always get a grid of the same width. With your wider document the grid stays the same but now doesn't fill the whole space. If you want it to stretch the whole width, you'll have to remove the width value of the column field so it can automatically adjust. If the the issue is that the grid is off to the side rather than in the center, you can change the location that GuideGuide renders grids in the settings (the gear) menu.

**Comment by SandorMax** [comment]
Wow! Thanks for getting back to me so quickly. I'm not sure why but when I left a couple of fields blank the app ended up rendering the grid I was looking for. FYI - 
![guides](https://cloud.githubusercontent.com/assets/10453015/5670139/4f85d6ea-974b-11e4-946c-95d641eb4dd9.png)
here's what the fields looked like…cheers

**Comment by cameronmcefee** [comment]
Hmm, that's strange but I'm glad to hear it got you the correct result eventually. If you notice more erratic behavior please let me know.
