### ISSUE TITLE
GuideGuide installed but not showing up in extensions dropdown on CC2014

### ISSUE THREAD

**Issue by alexandramolloy** [guideguide/support#101]
The extensions section (in view) is grey-ed out. I reinstalled and when I install it the manager says that it conflicts with "the following extensions." But it does not list any extensions. Then it drops me into my manager which says it is installed. But then (even after restarting PS) the extensions dropdown is grey-ed out.

**Comment by cameronmcefee** [comment]
Heh, this is a common and annoying issue with the Extension Manager. The issue lies in the relationship of Photoshop CC to Photoshop CC 2014. The first step to resolving it is to understand that the Extension Manager will install GuideGuide in both separately, but it remembers them together as one. Most likely you used to have GuideGuide installed in CC. When 2014 came out you uninstalled CC, but left GuideGuide. Unfortunately, the Extension Manager still remembers that GuideGuide is there, but it doesn't show the CC list of Extensions anymore.

The cleanest path to solving the problem (though annoying) is to reinstall Photoshop CC, which will give you the list of extensions again. You will then be able to uninstall the old version of GuideGuide. At that point you can uninstall CC and install the new version of GuideGuide.

**Comment by alexandramolloy** [comment]
Thanks so much!

*----*

+ 415.806.6761
+ www.alexmolloy.com
+ alex@alexmolloy.com
+ www.linkedin.com/alexmolloy <http://www.linkedin.com/in/alexmolloy>
+ @alexandramolloy <http://twitter.com/alexandramolloy>

**Comment by cameronmcefee** [comment]
@alexandramolloy I'm going to close this for now. Feel free to reopen if you aren't able to resolve the issue.

**Comment by alexandramolloy** [comment]
Hey Cameron -
Just getting to this and I am not sure where I can reinstall Photo CC. When I go
on Adobe it only gives the option to download latest version.
Best,Alex
----


+ 415.806.6761
+ www.alexmolloy.com [http://www.alexmolloy.com]+alex@alexmolloy.com [alex@alexmolloy.com]
+ www.linkedin.com/alexmolloy [http://www.linkedin.com/in/alexmolloy]
+ @alexandramolloy [http://twitter.com/alexandramolloy]

On Mon, Jan 12, 2015 at 10:46 AM, Cameron McEfee< notifications@github.com [notifications@github.com] > wrote:
@alexandramolloy [https://github.com/alexandramolloy] I'm going to close this for now. Feel free to reopen if you aren't able to
resolve the issue.

—
Reply to this email directly or view it on GitHub
[https://github.com/guideguide/support/issues/101#issuecomment-69621919] .

**Comment by cameronmcefee** [comment]
@alexandramolloy check out [this guide](https://helpx.adobe.com/creative-cloud/help/install-apps.html#previous). It should help you install older versions of Adobe apps.
