### ISSUE TITLE
Panel takes a long time to load options in GuideGuide 3.1.2

### ISSUE THREAD

**Issue by Gespinha** [guideguide/support#107]
Hi there,

Ever since I installed the latest version of GuideGuide I've noticed it has gotten a lot slower to display the options in the panel.

I turn Photoshop on, then click on the GuideGuide panel and its empty for about 3-4 seconds, then the options display.

Is this normal? Its really annoying and not helpful to have to wait that time for a panel to display its options.

Thanks in advance ;)

**Comment by cameronmcefee** [comment]
Hi @Gespinha,

Thanks for the feedback. I'm sorry to hear that the speed of GuideGuide annoys you. Hopefully future improvements may solve this. If you find it too crushing you your soul, the latest version of Photoshop CC 2014 now includes a tool that is very similar to GuideGuide which will likely load much faster since it's native. You can find it at View > New Guide Layout.
