### ISSUE TITLE
GuideGuide 3.1.2  invoking CC2014 "Rebuilding Histograms" every time PS window is touched

### ISSUE THREAD

**Issue by pmilez** [guideguide/support#110]
Disabling the plugin guide guide fixed an issue I have been having with Photoshop CC2014 where every touch of an open window caused a "rebuilding histogram" task to be invoked. 
That can take up to 30 seconds for a 6GB layered image. I reported the problem to adobe and Chris Cox replied suggesting it sounded similar to a 3rd party plugin issue in 2012. 
I disable guideguide 3.1.2 and the  "rebuilding histogram" problem disappeared. My work colleague also had this issue on his mac and it was also fixed by disabling guideguide. 

Me MacPro OS10.7 Photoshop CC2014. My colleague: MacbookPro2013 OS10.9.5 Photoshop CC2014

Link to Adobe problem report thread....
http://feedback.photoshop.com/photoshop_family/topics/photoshop-cc2014-now-long-wait-while-photoshop-builds-histograms?utm_source=notification&utm_medium=email&utm_campaign=reply_like&utm_content=topic_link

Regards
Peter Miles

**Comment by cameronmcefee** [comment]
Hi @pmilez,

Thanks for the report. At first glance I would guess this isn't a GuideGuide bug because GuideGuide doesn't do anything with histograms. However, uninstalling it fixes the issue, as you've mentioned. I've replied to your adobe thread to see if I can work with them to figure out what's going on.

**Comment by cameronmcefee** [comment]
This has been fixed in 3.1.3 http://guideguide.me/
