### ISSUE TITLE
Unable to install extension - PS CC 2014 64bit

### ISSUE THREAD

**Issue by robbaumgardner** [guideguide/support#113]
Whenever I try to install the extension I get the following error:

![guide_guide_error](https://cloud.githubusercontent.com/assets/6155871/6223522/3f071978-b631-11e4-8c9b-3f35f0e1c765.jpg)

I've searched my entire PC and no other version of the extension exists. Both PS and the extension manager are up to date.

**Comment by cameronmcefee** [comment]
Hi @robbaumgardner,

The conflict is an annoying Extension Manager bug. The problem is that the Extension Manager still remembers that GuideGuide is still installed in Photoshop CC, even though it's not there anymore. The trick to fixing it is to [reinstall Photoshop CC](https://helpx.adobe.com/creative-cloud/help/install-apps.html#previous), uninstall GuideGuide, uninstall Photoshop CC, then install GuideGuide which should now work fine.

**Comment by robbaumgardner** [comment]
Ok so I tried to do as you described.
1) Uninstalled PS CC 2014
2) Uninstalled Extension Manger
Note: GuideGuide was never installed so I could not uninstall it.

3) Reinstalled PS CC 2014
4) Reinstalled Extension manager CC

Result: The exact same issue with trying to install GuideGuide.

**Comment by cameronmcefee** [comment]
Hi @robbaumgardner,

Sorry, there was some miscommunication. Here's what you need to do.

- Install PS CC
- In the extension manager, click on PS CC in the sidebar. You should see GuideGuide there. Uninstall it.
- Install latest GuideGuide.

Bonus:

- Uninstall PS CC if you wish.

Note, that this all involves PS CC, not PS CC 2014. The conflict comes with the old version of Photoshop, not the new one.

**Comment by cameronmcefee** [comment]
Closing as stale
