### ISSUE TITLE
Crashes Photoshop CS6 Mac

### ISSUE THREAD

**Issue by abaney** [guideguide/support#115]
I tried restarting my computer, and opening PS. Still didn't help. After uninstalling GuideGuide, Photoshop stops crashing, and runs normal. Crashed with GuideGuide 3.1.2 and crashes with 3.1.3 using PS CS6 on a Mac (v.10.7.5).

![ps version](https://cloud.githubusercontent.com/assets/2255186/6333131/dd363b9a-bb47-11e4-9f2d-ab369ccbc2af.png)

**Comment by cameronmcefee** [comment]
Hi @abaney,

From my investigations and talking to a few other Photoshop panel developers about the issue you mention, it appears to be a known Photoshop bug. Unfortunately the specific cause of the bug is unknown so I can’t work around it and Adobe isn’t actively developing CS6 so it’s unlikely it will be fixed.

The bug appears to be dependent on the users system, since it only exists for a small group of people. I’ve heard that uninstalling Photoshop using the Adobe uninstaller and reinstalling it can possibly fix the issue, but this isn’t guaranteed.

One option is to install GuideGuide 2 which was built with different technology that doesn’t run into the bug. You can find old versions of GuideGuide here: http://guideguide.me/versions/

Alternatively, if you’ve been contemplating upgrading, the bug you’re experiencing doesn’t exist in Photoshop CC 2014. If you’ve been considering it, CC 2014 is a pretty good upgrade worth making the leap for.

Sorry I can’t provide a fix, but hopefully one of the above options will suffice.
