### ISSUE TITLE
3.1.3: Tabbing between fields doesn't work

### ISSUE THREAD

**Issue by BevansDesign** [guideguide/support#118]
I just downloaded the new version, and it's MUCH more responsive than the previous! Loving it so far, but using the Tab key to switch between fields doesn't seem to be working.

**Comment by cameronmcefee** [comment]
Hi @BevansDesign, thanks for the compliments. Unfortunately the tab thing is a photoshop bug. Unfortunately x2, the bug is in a global code library within the the Adobe universe, which means the team that works on it moves very slow as they have to account for many applications. I've talked with one of their people who has said the bug is known, the fix is on the way, but the release date is unknown.
