### ISSUE TITLE
Problem to install Guideguide 3.1.3.zxp in PS CC2014.2.2

### ISSUE THREAD

**Issue by etcaetera** [guideguide/support#119]
Problem to install Guideguide 3.1.3.zxp in PS CC2014.2.2
Adobe Extension manager CC version 7.3.2.39

It's told me signature isn't valid. So it couldn't proceed to install.
What i can do ? Thanks

**Comment by cameronmcefee** [comment]
Hi @etcaetera,

I've confirmed that the signature is valid and have successfully installed 3.1.3, so the problem is likely something in the apps you have installed. First, let's confirm a few things.

- Double check that you're in fact trying to install from *3.1.3-guideguide.zxp* and not another older version you might have laying around.

- While the version numbers you mention are the latest versions (that's good), some times a different version of the Extension Manager launches depending on what you have installed. When you double click the .zxp file, can you confirm that the CC version of the Extension Manger is the one that launches?

If those two things are confirmed, then I'd suggest trying to reinstall the Extension Manager. If that doesn't work, you can try unchecking *Tools > Preferences > Allow Extension Manager to access Internet* before you install. I've heard that works around "invalid signature* bugs.

**Comment by etcaetera** [comment]
Tools > Preferences > Allow Extension Manager to access Internet before you install.

Solved my issue ! All the versions i had mention was the right number. THANKS for the Tools uncheck fix

**Comment by etcaetera** [comment]
Tools > Preferences > Allow Extension Manager to access Internet before you install.

Solved my issue ! All the versions i had mention was the right number. THANKS for the Tools uncheck fix

**Comment by cameronmcefee** [comment]
No problem. Sadly that's just a workaround rather than a fix, but at least it works. Happy guiding.
