### ISSUE TITLE
Extension cannot be installed

### ISSUE THREAD

**Issue by juanstereo** [guideguide/support#120]
![screen shot 2015-03-02 at 1 15 10 pm](https://cloud.githubusercontent.com/assets/11277679/6448285/788eee7a-c0de-11e4-8d7d-b0a9c780ad48.png)

I've updated my Photoshop to the latest version and I keep getting this message. It's happen on two of my machines. Any guidance would be appreciated.

**Comment by cameronmcefee** [comment]
Hi @juanstereo,

This is fairly common confusion caused by the way the Extension Manager launches depending on what's on your computer. If you look at the left sidebar in the screenshot, you'll see Photoshop is not in the list. You'll also note at the top that this is the CS6 Extension Manager. My guess is that you have Photoshop CC or CC 2014, correct? In those releases Adobe stopped installing the CC Extension Manager by default, so you will need to download it from Creative Cloud. Once that's installed, you can install GuideGuide there which should solve your issue.

1. Open the Creative Cloud application manager.

2. Find and install Extension Manager CC

3. Double click the guideguide .zxp file.

4. Confirm that it launches the CC version of Extension Manager

5. :sparkle: :tada:

**Comment by juanstereo** [comment]
Thanks @cameronmcefee will give that a try.

**Comment by mitchy18** [comment]
![screenshot 2015-03-14 01 16 51](https://cloud.githubusercontent.com/assets/11471814/6650915/36267a0e-c9e8-11e4-8427-f36b71cecaa9.png)

I got the same problem and I have the newest version of Photoshop CC and the Extension Manager is the CC Version. Can I get some help please?

**Comment by juanstereo** [comment]
See @cameronmcefee instructions above, that solved the problem for me.

**Comment by cameronmcefee** [comment]
Hi @mitchy18,

I'm guessing you either do not have a CC version of Photoshop but are trying to install it in CC (your screenshot shows the Extension Manager CC), or your version is out of date.

![monosnap 2015-03-16 09-24-01](https://cloud.githubusercontent.com/assets/72919/6670824/310bc614-cbbe-11e4-8213-7cc08bac7010.jpg)

**Comment by rich0710** [comment]
Hi
I'm having exactly the same problem. I have PS cc and have downloaded the latest version of Adobe Extension Manager. I am not sure of how Extension Manager should look but I would think that the LH menu under Products should show PS cc but it doesnt. Can you tell me where I am going wrong please?
![guide](https://cloud.githubusercontent.com/assets/11698543/6882676/ab69d614-d585-11e4-8e7d-e19f68b0846d.jpg)

**Comment by cameronmcefee** [comment]
> I would think that the LH menu under Products should show PS cc but it doesnt

@rich0710, you're correct, that should show Photoshop. Unfortunately, I can't tell you why it's not there, since that's something depending on your system and unrelated to GuideGuide. You can try uninstalling and reinstalling both the Extension Manager and Photoshop via the Creative Cloud Application Manager and see if that fixes it. Otherwise, you'll need to work with Adobe to troubleshoot it.
