### ISSUE TITLE
define gutter width based on column width?

### ISSUE THREAD

**Issue by mjot** [guideguide/support#121]
Hi,

I would like to achieve the following. I wan't a grid with 12 columns and 11 gutters between. I don't have any special document size. Is it possible to configure GuideGuide to create a grid with 12 columns and a gutter with the width of 1/4 of a column?

This would help so much for responsive designs. Thanks for your help!

**Comment by cameronmcefee** [comment]
Hi @mjot,

Nice challenge. You put my algebra skills to the test. In fact, I had to [use a calculator](http://www.mathpapa.com/algebra-calculator.html).

So GuideGuide doesn't have what you're asking for built in, insomuch as you can't say "the gutter is as wide as 25% of the column width". However, GuideGuide supports percentage units, so with some algebra you can come up with the percentages needed to get your result. First, we need to figure out what a column's width is. That works out to this equation:

`(x*12) + ((x*.25)*11) = 100`

Which equates to `6.779661`. So we know a column is 6.78% wide. Now to figure out the gutters.

`(100 – (6.78*12)) / 11`

Which equates to `1.694545`. So we know the gutter is 1.695% wide. If you want to check if the math is right…

`1.695 / 6.78` comes out to `.25` :sparkles:.

Now, GuideGuide will automatically calculate the width of the columns for you, so all you need to do is specify 12 columns and a gutter width of 1.695%.

*Note: GuideGuide rounds pixels to make sure your columns are pixel accurate. When that calculation doesn't divide evenly across the columns (for example 3 columns from 10 pixels), it distributes the remainder amongst the columns. Because of this, your gutters, depending on on which ones you sample, may end up being +/- 2%*

**Comment by mjot** [comment]
Hi @cameronmcefee,

thanks for your example how to calculate this. :) I've done it the same way and so our results are the same. :) What I would like to ask, would it be possible to extend GuideGuides function to do it automatically? Im thinking about a setting "gutter position" with values like "split" and "between".

If someone chooses "between" than it's clear that with 12 columns there need to be only 11 gutters. (column count - 1). So I would enter 12 columns and gutter size 1/4 or 0.25.

What do you think about this?

Thanks

**Comment by cameronmcefee** [comment]
Ah, gotcha. Sorry for telling you what you already know :grin:. This is the first request I've ever had for that sort of thing. In my personal experience I've never wanted to base my gutters on the column width, mainly because gutters are usually tied more closely to the leading of the text within them than columns than the width of the columns themselves (again, my own experience).

At this point, my personal opinion is that the additional UI needed to facilitate such a feature would be more detrimental to the interface than the benefit it would provide (given my assumptions of how often it would be used). An alternative to UI would be a special unit type, for example  `.25w`, that would work in the gutter field that would indicate "based on column width", However this would need a bit more thought as it would need to work universally with Rows, and would require a decent refactor to the logic that generates the grid. I'll keep an ear open for other similar requests and will consider it further if it turns out to be a common desire.

> Im thinking about a setting "gutter position" with values like "split" and "between"

I'm curious what you mean by this. Since gutters are always `cols – 1`, they can always be described as between. Is this the difference you're implying between "split" and "between"?

```
           Between

| -- col -- | g | -- col -- |
|           |   |           |
|           |   |           |
|           |   |           |


            Split
            
| ---------- col ---------- |
|           | g |           |
|           |   |           |
|           |   |           |            
```
