### ISSUE TITLE
GuideGuide for Sketch?

### ISSUE THREAD

**Issue by surfingsquibb** [guideguide/support#124]
I love GuideGuide. I used to use it all of the time in PSD. But now the majority of my workflow is in Sketch. Is there any interest in creating a GuideGuide plugin for Sketch? (my entire design team of 7 would like to thumbs up this request). Thanks—cheers for creating such a useful tool.

**Comment by cameronmcefee** [comment]
Hi @surfingsquibb,

It's something semi-regularly requested and something I'd love to try. However, since GuideGuide's a hobby it moves only as quickly as the rest of my life allows. My current project is an official UI update for Photoshop panel, after which I'll start considering what's next, either an AI port or maybe Sketch.

From what I can tell, Sketch has a very different extension architecture, one that seems less customizable (using popups rather than actual panels/sidebars). Creating a Sketch version of GuideGuide will likely involve a lot of research and planning to figure out how it can fit into the Sketch flow, one I'm not personally familiar with. That is to say, I'd love to do it but don't get your hopes up any time soon.
