### ISSUE TITLE
technical issue with the gride

### ISSUE THREAD

**Issue by morant84** [guideguide/support#126]
Hi there
I've installed GuideGuide  to my Photoshop CC. for some reason I don't understand the grid values. I've inserted are showing strangely out side of my canvas boundaries.
pls see print screen bellow and thanks in advanced!

![screenhunter_1448 apr 19 18 51](https://cloud.githubusercontent.com/assets/12020430/7220129/5583f99a-e6c5-11e4-9fe5-bf06e224b431.jpg)

**Comment by cameronmcefee** [comment]
Hi @morant84,

Your document appears to be smaller than the grid you're trying to create, which causes unintended side effects in the calculations. For example, your document looks to be a little over 1200px wide, which equates to ~42.5cm, however you're trying to create 140cm margins. Since 140 > 42.5, the grid line for that will end up 97.5cm beyond the document.

My guess is that you either made the wrong size document or you aren't intending to use cm as your unit type.

**Comment by morant84** [comment]
yeah.. silly me. as you guessed I haven't notice the grid values was cm.
Thanks a lot for the quick and useful reply!

**Comment by cameronmcefee** [comment]
No problem, I'm glad that worked out!
