### ISSUE TITLE
guideguide not disturbuting guides evenly

### ISSUE THREAD

**Issue by kubb1234** [guideguide/support#134]
Hi,
I just installed for Photoshop CC 2014 and when using for some reason the guides do not distibute evenly across my document. This seems like it should be pretty straight forward. I'm following along with this lesson on Lynda.com also but the results are not what I'm expecting. I have a 1280 px wide document and keying in the #s indicated in the screen capture yet the 140 px right margin is clearly not setting properly, which in turn is throwing the entire grid off. Any ideas why this might be happening? Thanks.
![guideguidenotworking](https://cloud.githubusercontent.com/assets/12862982/8134286/c13a26e0-10e2-11e5-915a-4c7680decd01.png)

**Comment by cameronmcefee** [comment]
Hi @kubb1234,

The issue is that the sum of the grid you create (if you do the math of what is filled in the form) is not as wide as the document itself. By default GuideGuide is left aligned in these cases, but you can change it so it centers the grid. See related: https://github.com/guideguide/support/issues/132
