### ISSUE TITLE
Guide Guide v 3.1.4 not working in photoshop cc2015

### ISSUE THREAD

**Issue by streetevens** [guideguide/support#135]
Extension Manager cc is the latest version.
I tried to manually install GuideGuide, from the website http://guideguide.me/, but not.

**Comment by cameronmcefee** [comment]
I'm sorry to hear that. Can you be more specific about what is not working?

**Comment by PasqualeFS** [comment]
If he's like me, I'm getting a popup after following the instructions you posted for CC 2015.  I did all of this for Mac:

----------------------------------------------------------------------------------------------------------------------------------
Installation instructions

If you have the Extension Manager and Photoshop CC or CC 2014 installed, when you install the CC version of GuideGuide in one of those versions, Photoshop CC 2015 should also have GuideGuide (they install in the same places).

If you do not have either of those installed, you will need to manually install GuideGuide.

    Download the zip file above and unzip it.

    Copy the unzipped GuideGuide folder to the following directory:

    Windows 64: C:\Program Files (x86)\Common Files\Adobe\CEP\extensions\
    Windows 32: C:\Program Files\Common Files\Adobe\CEP\extensions\
    OSX: /Library/Application Support/Adobe/CEP/extensions/

    Restart Photoshop. You’ll find GuideGuide at Window > Extensions > GuideGuide
----------------------------------------------------------------------------------------------------------------------------------

After doing all of that and restarting, GuideGuide is in my list of extensions but when I try to access it for use, there's a popup that says:
"The GuideGuide extension could not be loaded because it was not properly signed".

Any thoughts on how to fix this?  I rely heavily on GuideGuide each day and that's the last damned time I upgrade CC.  I am having serious delays in my work due to this loss.

**Comment by cameronmcefee** [comment]
@PasqualeFS This is a weird question, but do you have any service like Google Drive or dropbox syncing the folder where GuideGuide is installed? That would potentially corrupt GuideGuide's signature.

**Comment by cameronmcefee** [comment]
Can you also confirm that your directories look like this?

![guideguide 2015-06-16 08-12-38](https://cloud.githubusercontent.com/assets/72919/8186498/7af72a3c-13ff-11e5-90c0-62ffedf4b5ef.jpg)

**Comment by PasqualeFS** [comment]
No, I don't.  This is a company computer so I'm not sure if they have anything syncing with that folder.  I've gone ahead and reverted back to CC 2014.  I love this app, Cameron.  When designing HTML email layouts or slicing them up, it allows me to have pixel perfect accuracy in my slices and then I just export layers to files and piece it back together with the HTML.  When I was introduced to GuideGuide in early 2014, it saved my life and a ton of time.  Hoping there's a fix for 2015.  If not, I'll just keep with the older version.  If it ain't broke, don't fix it, right?

**Comment by cameronmcefee** [comment]
@PasqualeFS I'm glad you're such a die hard fan. Can you confirm that your folders look like the screenshot above? It's *absolutely critical* that the contents of the folder do not change when you copy them, as the signature will be invalid (the warning) if it does not match what's in the folder.

**Comment by PasqualeFS** [comment]
As far as I can tell, they're exactly the same.

On Jun 16, 2015, at 3:34 PM, Cameron McEfee <notifications@github.com<mailto:notifications@github.com>> wrote:


@PasqualeFS<https://github.com/PasqualeFS> I'm glad you're such a die hard fan. Can you confirm that your folders look like the screenshot above? It's absolutely critical that the contents of the folder do not change when you copy them, as the signature will be invalid (the warning) if it does not match what's in the folder.

-

**Comment by Breklin** [comment]
Removing the old version and copying in a fresh version fixed that error for me.

**Comment by DavidV-WPCK** [comment]
@Breklin , same here!
Seems the Ext Manager has been dropped now for 2015 in favor of the "Exchange".

**Comment by cameronmcefee** [comment]
I'm glad to hear you've found a solution!

> Seems the Ext Manager has been dropped now for 2015 in favor of the "Exchange".

This is correct. GuideGuide will ultimately end up there, but currently violates a few of their policies that prevents it from being submitted.

**Comment by streetevens** [comment]
@cameronmcefee Thanks for your reply.  
It's exactly the same @PasqualeFS . I think my folder directories is right.  T_T
Thank you for your support !

**Comment by RanganaC** [comment]
similar issue here . Ones i installed Guide guide and it worked fine. but then i updated  it to new version and mistakenly i have deleted the guide guide old folder from the extension folder. now even i installed the latest version as per their directions, photoshops says
 "The GuideGuide extension could not be loaded because it was not properly signed."

Please help. This is really urgent!! :(

**Comment by cameronmcefee** [comment]
@streetevens can you [create a new issue](https://github.com/guideguide/support/issues/new) so I can investigate?

**Comment by Davox08** [comment]
Similar issue too, I create the next route: C:\Program Files (x86)\Common Files\Adobe\CEP\extensions (I have Windows 8.1 x64) and y put the GuideGuide folder in there. Everything works now.

**Comment by digitalle** [comment]
Any update on when/if the extension will be live in the CC 2015 online extension manager - have the same issue as above that "The GuideGuide extension could not be loaded because it was not properly signed."

thanks!

**Comment by cameronmcefee** [comment]
Hi @digitalle,

That error happens when you modify the contents of GuideGuide's files. Be sure you're copying the `GuideGuide` folder without changing anything.
