### ISSUE TITLE
cc2015 - more than one grid?

### ISSUE THREAD

**Issue by mipaulsen** [guideguide/support#138]
Hi, 

I have a question for you; is it possible to one grid for each artboard?

**Comment by cameronmcefee** [comment]
Hi @mipaulsen,

Yes, it is possible, though doesn't work as expected yet. I was caught of guard and haven't fully built in support for artboards yet. How to make it work:

1. Draw a selection that outlines the whole artboard in which you'd like to make your grid.
2. Use GuideGuide as normal.

If you draw a selection, GuideGuide uses it for its calculation rather than the document.

**Comment by mipaulsen** [comment]
Thanks for you're answers @cameronmcefee, but I can't see how this should work? Maybe I'm not doing it properly, because when I try to move my second artboard, the grid is still within my first artboard and not showing in the second...

**Comment by cameronmcefee** [comment]
Hi @mipaulsen,

Any chance you can outline your workflow for what you're trying to do step-by-step? I have a feeling the way you are trying to use GuideGuide is different from the way it actually works. If I know your process I can explain how to modify it to work.

**Comment by mipaulsen** [comment]
I can show you a picture, @cameronmcefee.

![skjermbilde 2015-06-17 kl 08 37 26](https://cloud.githubusercontent.com/assets/12917614/8200970/34f551a8-14cc-11e5-8c87-a9674c32c2c9.png)

As you can see, the grid is perfectly matched to artboard 1, but when I duplucate artbord 1 and move it to the right, the grid doesn't follow along as you see of my screen shot...

**Comment by cameronmcefee** [comment]
Hi @mipaulsen,

Thanks for the clarification! Guides exist relative to the document coordinate plane, not the artboard. When you move an artboard, the guides stay where they are because they don't have any sort of direct connection to the artboard itself. It possible in the future GuideGuide could try to regenerate a grid when it moves, but at this time it cannot do that.

For the time being, the required workflow, assuming your goal is to move an artboard *and* have a grid in it, is to put the artboard where you want it, then create your grid. If you need to move the artboard you must remove your guides, move the artboard, then generate the grid at the new location.

Worth noting: I just [published an update](http://guideguide.me/) to add basic artboard support to GuideGuide. If you install the latest version, when you use GuideGuide, it'll generate the grid at the location of your currently selected artboard(s).
