### ISSUE TITLE
GuideGuide not showing in Photoshop CC 2015

### ISSUE THREAD

**Issue by SarahFishr** [guideguide/support#143]
I've installed the latest versions of Photoshop, Adobe Extension Manager and GuideGuide and the extension is showing up in Adobe Extension Manager, but when I go to Window > Extensions in Photoshop it doesn't appear. Any ideas on how I can fix this please? Thanks!
![screen shot 2015-06-19 at 10 47 06](https://cloud.githubusercontent.com/assets/12965091/8251003/a17ddaf2-1670-11e5-98a1-efb467967b6f.png)
![screen shot 2015-06-19 at 10 47 17](https://cloud.githubusercontent.com/assets/12965091/8251002/a17d260c-1670-11e5-9873-d802dec700af.png)

**Comment by cameronmcefee** [comment]
Hi @SarahFishr,

To be honest, I'm baffled about how you were able to get that screenshot. Adobe, to the extent of my knowledge, removed support for the Extension Manager from Photoshop CC 2015, so as far as I know, your screenshot is a fake! I'm kidding about the fake part, but I am serious about not knowing how you managed that. Since what you're doing is beyond what I know to be possible, I can't really help with that.

However, if you have a look at the install instructions for the CC 2015 version of GuideGuide [on the site](http://guideguide.me/), it explains how to install it manually. If you follow those instructions you'll likely resolve the issue.

I would also suggest uninstalling GuideGuide from the extension manager. While I don't expect it will cause any conflicts, it may cause some confusion in the future if you try to uninstall GuideGuide from that location and forget that you also installed it manually.

**Comment by SarahFishr** [comment]
That’s very strange, I didn’t realise support had been removed for Extension Manager, but that probably explains why it wasn’t working… after uninstalling Extension Manager it’s now all working fine!

Thanks for your help, Sarah

> On 19 Jun 2015, at 16:08, Cameron McEfee <notifications@github.com> wrote:
> 
> Hi @SarahFishr <https://github.com/SarahFishr>,
> 
> To be honest, I'm baffled about how you were able to get that screenshot. Adobe, to the extent of my knowledge, removed support for the Extension Manager from Photoshop CC 2015, so as far as I know, your screenshot is a fake! I'm kidding about the fake part, but I am serious about not knowing how you managed that. Since what you're doing is beyond what I know to be possible, I can't really help with that.
> 
> However, if you have a look at the install instructions for the CC 2015 version of GuideGuide on the site <http://guideguide.me/>, it explains how to install it manually. If you follow those instructions you'll likely resolve the issue.
> 
> I would also suggest uninstalling GuideGuide from the extension manager. While I don't expect it will cause any conflicts, it may cause some confusion in the future if you try to uninstall GuideGuide from that location and forget that you also installed it manually.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/guideguide/support/issues/143#issuecomment-113542528>.
> 



Sarah Fisher / Graphic Designer 

Rockit Design Ltd 
023 8033 3991 / rockitdesign.co.uk <http://www.rockitdesign.co.uk/> 
Facebook <https://facebook.com/rockitdesign> / Twitter <https://twitter.com/RockitDesignLtd> / Pinterest <https://pinterest.com/rockitdesign/> / Google+ <https://plus.google.com/108468981699352784797/about> 

The Chapel, Cemetery Road, Southampton, SO15 7NN. Registered in England & Wales No. 7104337.

**Comment by cameronmcefee** [comment]
> after uninstalling Extension Manager it’s now all working fine!

Lol that also doesn't make sense, but I've come to learn that in Adobe development life is full of surprises. I'm glad you got it working!
