### ISSUE TITLE
PS CC 2015 Guide Guide installation issue

### ISSUE THREAD

**Issue by haraldmuc** [guideguide/support#144]
I have upgraded to PS CC 2015 and lost my Guide Guide tool. In PS CC 2015 it does not work (and show up under extensions at all) when following the manual installation process. What to do? Thanks, Harald

**Comment by cameronmcefee** [comment]
Hi @haraldmuc,

Can you confirm your folders look like this?

![](https://cloud.githubusercontent.com/assets/72919/8186498/7af72a3c-13ff-11e5-90c0-62ffedf4b5ef.jpg)

**Comment by haraldmuc** [comment]
No. Where should this folder be located? (I'm using Win 7 on a PC)

**Comment by cameronmcefee** [comment]
These are the Windows install locations:

Windows 64: `C:\Program Files (x86)\Common Files\Adobe\CEP\extensions\`
Windows 32: `C:\Program Files\Common Files\Adobe\CEP\extensions\`

The key is that once you copy the folders over, it should look like *extensions > GuideGuide > all the guideguide files*. If it looks like *extensions > GuideGuide > GuideGuide > all the guideguide files* it won't work. I mention this because it's a common installation issue.

**Comment by haraldmuc** [comment]
Found it and copied the GuideGuide folder to the location you suggested. Now it works perfect! Thanks you very much. Harald

**Comment by cameronmcefee** [comment]
Glad to hear it!
