### ISSUE TITLE
GuideGuide not working on Photoshop CC 2015

### ISSUE THREAD

**Issue by cacaocom** [guideguide/support#146]
Using latest version of Extension manager (7.3.2.39) and latest update of Photoshop CC 2015, 
 I see the extension in photoshop but when I try to use it I have the message : "the extension can not be loaded since it is not well signed"

![1](https://cloud.githubusercontent.com/assets/12997427/8278865/32ef4e2a-18cf-11e5-8032-d888e253c6d3.jpg)

**Comment by cameronmcefee** [comment]
Hi @cacaocom,

Signature errors happen when something modifies the contents of the GuideGuide extension files.

- Do you have any service such as Box, Dropbox, or Google Drive syncing the folder or parent folders of the directory where the GuideGuide extension files exist?

- Did you copy the entire contents of the GuideGuide folder within the zip file?

- Did you modify the contents of the GuideGuide folder?

If none of these sound like something that may have modified the files, I'd suggest trying to reinstall GuideGuide, making sure to note whether anything modifies the files in the process. They must remain unmodified, otherwise the signature becomes invalid.

**Comment by cacaocom** [comment]
Thanks for your answer, I did it again and it worked this time...
Problem solved !

**Comment by cameronmcefee** [comment]
Glad to hear it!
