### ISSUE TITLE
No extensions folder on photoshop cc 2015

### ISSUE THREAD

**Issue by olcodesign** [guideguide/support#147]
Hi,

I have updated to Photoshop CC 2015, and trying to install you plug-in (which has been a lifesaver on cc2014). When I navigate to the CEP, there is no extensions folder, just a cache folder, so how do I install the plugin please?

**Comment by ssosina** [comment]
@olcodesign I have the same issue. I tried manually creating the folder but still does work.

**Comment by cameronmcefee** [comment]
Hi @olcodesign and @ssosina,

I'm guessing you are both on OSX, and the issue is likely that you are trying to install GuideGuide into your *personal* Library folder rather than the *system* Library folder. Running the following command in the terminal will open the correct folder for you:

`open /Library/Application\ Support/Adobe/CEP/extensions/`

**Comment by olcodesign** [comment]
Brilliant, thanks, this has solved my problem. @ssosina @cameronmcefee

**Comment by cameronmcefee** [comment]
:+1: glad to hear it.

**Comment by codeawe** [comment]
cameron -- pitty us lowly Win7-64 masses, now scratching our heads over whether you meant an actual DOS command prompt window.

**Comment by cameronmcefee** [comment]
Hi @codeawe,

The code above works in the OSX Terminal, their equivalent of the Windows command prompt. I give that instruction out because the OSX `/Library` folder is hidden by default. That command has been easier to communicate to people than it is to get the folder revealed and then browsable through the file tree.

As for Windows x64, the folder you're looking for is `C:\Program Files (x86)\Common Files\Adobe\CEP\extensions\`, which you should be able to navigate to through the regular Windows file browser.
