### ISSUE TITLE
GuideGuide opens, then crashes

### ISSUE THREAD

**Issue by ThatRedHead** [guideguide/support#182]
I'm having the exact same issue as #176, but I'm running Mac OS 10.10.5 with Adobe CC 2015.0.1. GuideGuide is installed correctly, and I've gone through the install-delete-reinstall process. If it opens in it's own panel or in an expanded panel, it's there for about 2 seconds (blank), then disappears.

**Comment by cameronmcefee** [comment]
Hi @ThatRedHead,

I'm sorry to hear of the trouble. How rude of me would it be to request that you try reinstalling Photoshop? In most cases the issue comes from something being weird/messed up with Photoshop that a reinstall usually will fix.

Have you been able to successfully use GuideGuide on earlier versions of Photoshop?

**Comment by ThatRedHead** [comment]
Well it's not rude if it works. Thankfully with the CC setup and fast internet uninstall/reinstall doesn't take long at all. That seems to have fixed it, thanks!

**Comment by cameronmcefee** [comment]
:tada: I'm glad to hear it!
