### ISSUE TITLE
help...

### ISSUE THREAD

**Issue by thomaslayland** [guideguide/support#195]
Hi, just bought guideguide but I can't for the life of me make a simple grid. the grid spacing seems to be way off and i dont really understand how it works, as simple as its supposed to be!

All I want to do is make a simple grid system similar to this
![grid](https://cloud.githubusercontent.com/assets/16313518/11828639/8576a874-a38e-11e5-88c0-74069d93710c.jpg)

any help or guidance is appreciated, thanks

**Comment by thomaslayland** [comment]
also is there any way to download already made grids by others?

**Comment by cameronmcefee** [comment]
Hi @thomaslayland!

What are the specific measurements of the various parts of the grid you want to make? The image you posted is a helpful illustration, but isn't particularly useful without knowing what the distance between the space are. For example, I can see there are four columns and four rows, each with gutters, but I don't know if you have a width and height for the document or if you want to base your document size on the width and height of the columns and rows. I also don't know what width you want the gutters to be. Basically if you can answer those questions, you put the answers into the GuideGuide form and GuideGuide will create the guides for you.

As for downloading other people's grids, it's possible if you have grids someone has exported from GuideGuide using the import feature. However there isn't any sort of community grids list, if that's what you're hoping for.

**Comment by thomaslayland** [comment]
Hi thanks for the fast reply, my page size is 8.5" x 11" (a magazine page) and I just wanted a simple grid like above. I'm not sure if my guideguide is correctly working, for example when I put the Rows as '5' and then click add guides, If I want to add '6' rows instead, I change it to '6' but it doesn't add 6 rows, it adds rows in random places?? Like this: 
![screen shot 2015-12-16 at 12 41 56](https://cloud.githubusercontent.com/assets/16313518/11841073/84f8f898-a3f2-11e5-8e3a-d5f247ba9d20.png)

**Comment by cameronmcefee** [comment]
Can you provide a screenshot that includes GuideGuide the way you've filled it out?

**Comment by thomaslayland** [comment]
Sure, this is an example, as you can see the guttering isn't even at
all?[image:
Inline image 2]

**Comment by cameronmcefee** [comment]
Unfortunately, you can't upload images when replying via email. You'll have to add it from the GitHub page specially.

**Comment by thomaslayland** [comment]
Apologies, image attached below.
![screen shot 2015-12-16 at 17 25 20](https://cloud.githubusercontent.com/assets/16313518/11850118/591381d6-a423-11e5-9400-f54eaf59bfaf.png)

**Comment by cameronmcefee** [comment]
Thanks for the screenshot @thomaslayland. From the looks of it, you ran GuideGuide twice, once with the settings you have there, and once without the gutter filled in (the "random" guides are the second grid without the gutter). GuideGuide only adds guides to whatever is already in your document (aka it doesn't clear the guides before adding a new grid). If you added a grid you don't like, you have to undo it or clear it before running GuideGuide again, otherwise you'll just add them on top of one another.

If you clear all the guides (the :no_entry_sign: button), then run GuideGuide as you have it filled out again, you should get what you're expecting.

![screen shot 2015-12-16 at 11 15 27 am](https://cloud.githubusercontent.com/assets/72919/11851288/b8139d5c-a3e6-11e5-8561-7b96eb1d3f1f.png)

**Comment by thomaslayland** [comment]
Cameron thanks so much, works perfectly, I didn't realise I had to scrap the previous guide before entering new digits! Thanks!

**Comment by cameronmcefee** [comment]
I'm glad it's working for you now. Best of luck!
