### ISSUE TITLE
No Guide inside selections

### ISSUE THREAD

**Issue by tzekin** [guideguide/support#197]
Hi I just downloaded the trial version of GuideGuide (v.4.1.5).

I have these two questions:
1. When I create a selection I am not able to add guides inside it. Non of the buttons or settings work. Mid point guide, left, right or any setting I enter and click the add guide button.
Is this a limitation of the trial? I am using photoshop CC2015 (v.16.0.1)

2. Is is possible to split the gutter in two halfs with a guide. What I mean is: Have a gutter of let's say 40px but in the middle of it have another guide that will split this gutter into two.

Thanks

**Comment by cameronmcefee** [comment]
Hi @tzekin,

Sorry for the trouble!

> 1. When I create a selection I am not able to add guides inside it. Non of the buttons or settings work. Mid point guide, left, right or any setting I enter and click the add guide button.
Is this a limitation of the trial? I am using photoshop CC2015 (v.16.0.1)

The trial hides features from you when it kicks in, so if you can see the buttons, they should work. Please provide a screenshot that includes your document, GuideGuide with the form filled out however you are using it, and the layer's palette.

You can also try zooming way out to see if the guides are being added in the wrong place. While this was supposed to be fixed in 4.1.5, it's possible I might have missed something.

> 2. Is is possible to split the gutter in two halfs with a guide. What I mean is: Have a gutter of let's say 40px but in the middle of it have another guide that will split this gutter into two.

Yep, definitely possible. Any of the fields that let you put in a measurement support [a limited form of grid notation](http://guideguide.me/documentation/guides/grid-notation-in-fields/). In your case, using `20px | 20px` in the gutter field would do what you're asking.

**Comment by tzekin** [comment]
Hi @cameronmcefee ,

Thank you for the fast reply. Here is the screenshot.

![image](https://cloud.githubusercontent.com/assets/8307906/12233197/cf6d13ac-b86d-11e5-8c21-f8bd36e921e5.png)


I tried with both having a locked background layer and with a single layer as in the screenshot. I also tried with an older version of photoshop (CC 2014). still no luck with adding guides within a selection. Zooming way out didn't reveal any guides.

The limited form of grid notation worked nicely. Thanks.

**Comment by cameronmcefee** [comment]
Thanks @tzekin, I'm able to confirm the issue. It looks like the issue only happens in documents without artboards. If you create your file with an artboard (just one is fine), the selections will work as expected. 

I'll work on a fix as soon as I can manage.

**Comment by tzekin** [comment]
Thank you @cameronmcefee. 

I look forward to a possible solution as artboards is not something I use that often.

**Comment by cameronmcefee** [comment]
I've published 3.1.6 with an update with the fix.

- If you're still using the trial, you'll need to download GuideGuide again from http://guideguide.me/.

- If you've purchased through Creative Market or Gumroad, you should have received an email by now with a link to download the latest version.

- If you've purchased through Adobe Add-ons, they unfortunately still have not approved earlier releases. I will submit 3.1.6 as soon as they'll let me.
