### ISSUE TITLE
Cannot install in photoshop CS5

### ISSUE THREAD

**Issue by siqve006** [guideguide/support#66]
When I try opening the guideguide.zxp, it says 'this extension cannot be installed. it requires photoshop version 12 or higher.

**Comment by cameronmcefee** [comment]
Closing this, since [GuideGuide 4](http://guideguide.me) is now out.

**Comment by Styloamna** [comment]
I have issue about to install guide guide.I have download guideguide from guideguide.me for Photoshop CS5 but when i ry to instal in adobe extension manager cs5 he say you have no permission to perform this action then after this error i have run photoshop as administration but the error remain same.Please give me the solution and advice to what version i have to download because i have Photoshop Cs5 extended.Reply fast......

**Comment by cameronmcefee** [comment]
Hi @Styloamna,

I'm sorry for the trouble. The current versions of GuideGuide no longer support CS5, and the issue described sounds like one that is related to the Extension Manager, not GuideGuide. I suggest contacting Adobe support.
