### ISSUE TITLE
Photoshop CC 2014 win 8.1 x64 doesn't work

### ISSUE THREAD

**Issue by DSkvar** [guideguide/support#98]
Hi i have problem - when i install GG, open PS and click on GG icon GG window showing for 0.5 sec then gone.... 

PS version 310x64 (up to date)  Extension man version 7.3.2.39
GG version 3.0.2 ..... help plz (

![default](https://cloud.githubusercontent.com/assets/6710115/5575239/16d9bfc4-8fde-11e4-8a5f-036dc05c5b28.jpg)

**Comment by DSkvar** [comment]
@cameronmcefee i try open/close it many times but it doesn't work.... just open for some moments and close... (

**Comment by Leighd7** [comment]
Have similar problem, panel opens when go to use it it just crashes photoshop with memory errors.

This has only happened since last update of PS cc 2014

**Comment by cameronmcefee** [comment]
@Leighd7 Would you mind [opening a new issue](https://github.com/guideguide/support/issues/new) and include your errors?

**Comment by cameronmcefee** [comment]
@DSkvar Can you confirm that both the Extension Manager and Photoshop are up to date?

![screen shot 2015-01-02 at 8 05 11 am](https://cloud.githubusercontent.com/assets/72919/5597390/690826da-9256-11e4-88bc-25ce48f5438e.jpg)

![screen shot 2015-01-02 at 8 07 05 am](https://cloud.githubusercontent.com/assets/72919/5597398/798b10bc-9256-11e4-961c-e0f97340d514.jpg)

**Comment by DSkvar** [comment]
@cameronmcefee 
![1](https://cloud.githubusercontent.com/assets/6710115/5602674/0081ff70-9367-11e4-9d1d-7fa95a8159f1.jpg)
![2](https://cloud.githubusercontent.com/assets/6710115/5602675/009c792c-9367-11e4-8194-426f2cade023.jpg)

**Comment by cameronmcefee** [comment]
I just realized you already confirmed those in your first message >.< Sorry about that @DSkvar. Are you still using 3.0.2 or do you have 3.1.2 installed? I can't help debug old versions, but I can try to debug the latest version (3.1.2).

**Comment by DSkvar** [comment]
@cameronmcefee i try 3.0,2 and 3.1.2 and both have thease problem (

**Comment by cameronmcefee** [comment]
@DSkvar I'm not sure if this will work, but could you try checking the [Windows Event Viewer](http://windows.microsoft.com/en-us/windows/open-event-viewer#1TC=windows-7) to see if there are any logs from Photoshop when you launch the panel? Try launching Photoshop, opening GuideGuide, then open the Event Viewer. Look under *Applications and Service Logs*, and check if there's any logged for Photoshop with a timestamp that looks like it happened when you launched GuideGuide.

Please note, I'm not sure if there will actually be any errors to find here. GuideGuide isn't set up to log errors like this, so I'm hoping it might catch them automatically.

If this doesn't work, I won't be able to debug much further at this time, unfortunately. However, I do know that the bug is a UI bug. I'm in the process of working on a new UI update which will most likely remove the bug you're experiencing once it is released.

In the mean time, if you need to be working, try using the built in guide tools in CC 2014. Photoshop now has a guide tool at View > New Guide Layout that works similarly to GuideGuide. It can do basic grids. About the only things you'll miss are GuideGuide's grid notation, and the quick midpoint buttons.

**Comment by DSkvar** [comment]
Now i think its problem with Ps beacause i try open Kuler plugin and have same problem )
Abode adobe....

**Comment by cameronmcefee** [comment]
Aw, well I'm sorry to hear that, though I'm happy to hear the issue doesn't appear to be with GuideGuide.

It's annoying, but I've found reinstalling Photoshop (using the Adobe uninstallers) sometimes resolves issues like the one you've mentioned. If you're desperate, that might be an option.
